# Generated by Django 4.1.6 on 2023-12-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacman', '0003_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='finalized',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
