# Generated by Django 4.1.6 on 2023-12-23 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pacman', '0004_challenges_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='challenge_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='challenge_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
